server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatisdb?serverTimezone=UTC
    username: root
    password: root
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  application:
    name: web-server
mybatis:
  type-aliases-package: com.emon.user.pojo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka/,http://localhost:10087/eureka/
#USER-SERVICE:  负载均衡策略
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netfilx.loadbalancer.RandomRule