server:
  port: 10086
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatisdb?serverTimezone=UTC
    username: root
    password: root
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  application:
    name: eureka-server
mybatis:
  type-aliases-package: com.emon.user.pojo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka/,http://localhost:10087/eureka/
    register-with-eureka: false
  server:
    eviction-interval-timer-in-ms: 30000